server:
  port: 8301
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloudstudy?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 500000
  application:
    name: borrow-service
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        ephemeral: false  #临时实例
        # 权重大小，越大越优先调用，默认为1
        #weight: 0.5
        cluster-name: Guangzhou
        namespace: f2c7711b-6df9-40c2-b83a-f608dec27a9a
    loadbalancer:
      nacos:
        #将loadbalancer的nacos支持开启,集成Nacos负载均衡
        enabled: true
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
        # 关闭Context收敛，这样被监控方法可以进行不同链路的单独控制
      web-context-unify: false
